# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT

echo -e "\n--- Atualizando pacotes ---\n"
sudo apt-get -qq update

#Variáveis para o MySQL - Apenas para máquina de desenvolvimento
#Altere para os dados que achar relevante
DBHOST=localhost
DBNAME=dbname
DBUSER=dbuser
DBPASSWD=dbpass

echo -e "\n--- Instalando e configurando MySQL ---\n"
debconf-set-selections <<< "mysql-server mysql-server/root_password password $DBPASSWD"
debconf-set-selections <<< "mysql-server mysql-server/root_password_again password $DBPASSWD"
sudo apt-get -y install mysql-server

mysql -uroot -p$DBPASSWD -e "CREATE DATABASE $DBNAME"
mysql -uroot -p$DBPASSWD -e "grant all privileges on $DBNAME.* to '$DBUSER'@'%' identified by '$DBPASSWD'"

systemctl enable mysql

sed -i "s/bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf
sudo service mysql restart

echo -e "\n--- Desinstalando openjdk atual e instalando openjdk-8 ---\n"
sudo apt-get -y purge openjdk*
sudo apt-get -y install openjdk-8-jdk

echo -e "\n--- Instalando e configurando Elasticsearch ---\n"
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.1.1.deb --progress=bar:force
sudo dpkg -i elasticsearch-6.1.1.deb
sudo bash -c 'echo "network.host: 0.0.0.0" >> /etc/elasticsearch/elasticsearch.yml'
sudo bash -c 'echo "transport.host: localhost" >> /etc/elasticsearch/elasticsearch.yml'
sudo bash -c 'echo "transport.tcp.port: 9300" >> /etc/elasticsearch/elasticsearch.yml'
sudo bash -c 'echo "http.port: 9200" >> /etc/elasticsearch/elasticsearch.yml'

echo -e "\n--- Instalando e configurando Logstash ---\n"
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
sudo apt-get install apt-transport-https
echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
sudo apt-get -qq update && sudo apt-get install logstash

echo -e "\n--- Iniciando Elasticsearch ---\n"
sudo systemctl enable elasticsearch.service
sudo systemctl start elasticsearch.service

echo -e "\n--- Tudo pronto, hora do show! ---\n"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 3306, host: 3306 #mysql
  config.vm.network "forwarded_port", guest: 9200, host: 9200 #elasticsearch
  config.vm.provision "shell", inline: $script
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 1
  end
end
