# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT

echo -e "\n--- Atualizando pacotes ---\n"
sudo apt-get -qq update

echo -e "\n--- Instalando Apache 2 ---\n"
sudo apt-get install -y apache2

echo -e "\n--- Definindo diretório da aplicação Laravel ---\n"
rm -rf /var/www/html
ln -s /vagrant /var/www/html
echo "cd /vagrant" >> /home/vagrant/.bashrc

echo -e "\n--- Instalando o PHP 7.2 ---\n"
sudo apt-get -y install python-software-properties
sudo add-apt-repository ppa:ondrej/php
sudo apt-get -qq update
sudo apt-get install -y php7.2 libapache2-mod-php7.2 php7.2-cli php7.2-common php-xdebug php7.2-fpm

echo -e "\n--- Configurando PHP.ini e Xdebug ---\n"
sudo sed -i "s/error_reporting = .*/error_reporting = E_ALL/" /etc/php/7.2/apache2/php.ini
sudo sed -i "s/display_errors = .*/display_errors = On/" /etc/php/7.2/apache2/php.ini
echo 'xdebug.remote_enable = 1' | sudo tee --append /etc/php/7.2/mods-available/xdebug.ini
echo 'xdebug.remote_autostart = 1' | sudo tee --append /etc/php/7.2/mods-available/xdebug.ini
echo 'xdebug.remote_port=9000' | sudo tee --append /etc/php/7.2/mods-available/xdebug.ini
echo 'xdebug.remote_connect_back=true' | sudo tee --append /etc/php/7.2/mods-available/xdebug.ini
netstat -rn | grep "^0.0.0.0 " | cut -d " " -f10 | awk -v x="xdebug.remote_host=" '{print x $1}' | sudo tee --append /etc/php/7.2/mods-available/xdebug.ini
sudo service apache2 restart

echo -e "\n--- Tudo pronto, hora do show! ---\n"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 80, host: 8000 #apache
  config.vm.provision "shell", inline: $script
end